// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: permission.proto

package permission

import (
	"context"

	"speedsterApi/app/permission/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PermissionTreeItem = pb.PermissionTreeItem
	PermissionTreeReq  = pb.PermissionTreeReq
	PermissionTreeResp = pb.PermissionTreeResp

	Permission interface {
		PermissionTree(ctx context.Context, in *PermissionTreeReq, opts ...grpc.CallOption) (*PermissionTreeResp, error)
	}

	defaultPermission struct {
		cli zrpc.Client
	}
)

func NewPermission(cli zrpc.Client) Permission {
	return &defaultPermission{
		cli: cli,
	}
}

func (m *defaultPermission) PermissionTree(ctx context.Context, in *PermissionTreeReq, opts ...grpc.CallOption) (*PermissionTreeResp, error) {
	client := pb.NewPermissionClient(m.cli.Conn())
	return client.PermissionTree(ctx, in, opts...)
}
