// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: permission.proto

package server

import (
	"context"

	"speedsterApi/app/permission/rpc/internal/logic"
	"speedsterApi/app/permission/rpc/internal/svc"
	"speedsterApi/app/permission/rpc/pb"
)

type PermissionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPermissionServer
}

func NewPermissionServer(svcCtx *svc.ServiceContext) *PermissionServer {
	return &PermissionServer{
		svcCtx: svcCtx,
	}
}

func (s *PermissionServer) PermissionTree(ctx context.Context, in *pb.PermissionTreeReq) (*pb.PermissionTreeResp, error) {
	l := logic.NewPermissionTreeLogic(ctx, s.svcCtx)
	return l.PermissionTree(in)
}

func (s *PermissionServer) GetRolePermissions(ctx context.Context, in *pb.RoleIdReq) (*pb.RolePermissionResp, error) {
	l := logic.NewGetRolePermissionsLogic(ctx, s.svcCtx)
	return l.GetRolePermissions(in)
}
