// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpc.proto

package role

import (
	"context"

	"speedsterApi/app/role/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssignDefaultRoleReq  = pb.AssignDefaultRoleReq
	AssignDefaultRoleResp = pb.AssignDefaultRoleResp
	UserRole              = pb.UserRole
	UserRoleResp          = pb.UserRoleResp

	Role interface {
		AddUserRole(ctx context.Context, in *UserRole, opts ...grpc.CallOption) (*UserRoleResp, error)
		AssignDefaultRole(ctx context.Context, in *AssignDefaultRoleReq, opts ...grpc.CallOption) (*AssignDefaultRoleResp, error)
	}

	defaultRole struct {
		cli zrpc.Client
	}
)

func NewRole(cli zrpc.Client) Role {
	return &defaultRole{
		cli: cli,
	}
}

func (m *defaultRole) AddUserRole(ctx context.Context, in *UserRole, opts ...grpc.CallOption) (*UserRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.AddUserRole(ctx, in, opts...)
}

func (m *defaultRole) AssignDefaultRole(ctx context.Context, in *AssignDefaultRoleReq, opts ...grpc.CallOption) (*AssignDefaultRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.AssignDefaultRole(ctx, in, opts...)
}
