// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type GetRolePermissionReq struct {
	RoleId int64 `json:"roleId"`
}

type PermissionListData struct {
	List  []PermissionListItem `json:"list"`
	Total int64                `json:"total"`
}

type PermissionListItem struct {
	Id       int64                `json:"id"`
	Name     string               `json:"name"`
	Code     string               `json:"code"`
	Path     string               `json:"path"`
	Method   string               `json:"method"`
	Type     int64                `json:"type"`
	Icon     string               `json:"icon"`
	Sort     int64                `json:"sort"`
	Status   int64                `json:"status"`
	ParentId int64                `json:"parent_id"`
	Children []PermissionListItem `json:"children"`
}

type PermissionListResp struct {
	Base
	Data PermissionListData `json:"data"`
}

type PermisssionListReq struct {
	Name string `json:"name,optional"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type RolePermissionData struct {
	PermissionIds []int64 `json:"permission_ids"`
}

type RolePermissionResp struct {
	Base
	Data RolePermissionData `json:"data"`
}
