// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg,omitempty"`
	Data interface{} `json:"data,omitempty"` // .api 中使用 any 对应 Go 的 interface{} 或 泛型 T
}

type RoleListReq struct {
	Rolename string `json:"rolename,optional"`
	Code     string `json:"code,optional"`
	Status   int64  `json:"status,optional"`
	PageNo   int    `json:"pageNo,optional"`
	PageSize int    `json:"pageSize,optional"`
}

type RoleListRsp struct {
	Name        string
	Code        string
	Desctiption string
	Status      int64
	CreateTime  string
	UpdateTime  string
}
