// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type DelRoleReq struct {
	Id int64 `json:"id,optional"`
}

type GetRolePermissionReq struct {
	RoleId int64 `json:"roleId"`
}

type LoginData struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	Time         string `json:"time"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Base
	Data LoginData `json:"data"`
}

type NewRoleReq struct {
	Name        string `json:"name,optional"`
	Code        string `json:"code,optional"`
	Description string `json:"description"`
}

type PermissionListData struct {
	List  []PermissionListItem `json:"list"`
	Total int64                `json:"total"`
}

type PermissionListItem struct {
	Id       int64                `json:"id"`
	Name     string               `json:"name"`
	Code     string               `json:"code"`
	Path     string               `json:"path"`
	Method   string               `json:"method"`
	Type     int64                `json:"type"`
	Icon     string               `json:"icon"`
	Sort     int64                `json:"sort"`
	Status   int64                `json:"status"`
	ParentId int64                `json:"parent_id"`
	Children []PermissionListItem `json:"children"`
}

type PermissionListResp struct {
	Base
	Data PermissionListData `json:"data"`
}

type PermisssionListReq struct {
	Name string `json:"name,optional"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken,optional"`
}

type RegisterData struct {
	UserId string `json:"user_id"`
}

type RegisterReq struct {
	Username string  `json:"username"`
	Password string  `json:"password"`
	Email    *string `json:"email,optional"`
	Phone    *string `json:"phone,optional"`
}

type RegisterResp struct {
	Base
	Data RegisterData `json:"data"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type RoleListData struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Desctiption string `json:"desctiption"`
	Status      int64  `json:"status"`
	CreateTime  string `json:"create_time"`
	UpdateTime  string `json:"update_time"`
}

type RoleListReq struct {
	Rolename string `json:"rolename,optional"`
	Code     string `json:"code,optional"`
	Status   int64  `json:"status,optional"`
	PageNo   int64  `json:"pageNo,optional"`
	PageSize int64  `json:"pageSize,optional"`
}

type RoleListResp struct {
	Base
	Data RoleListData `json:"data"`
}

type RolePermissionData struct {
	PermissionIds []int64 `json:"permission_ids"`
}

type RolePermissionResp struct {
	Base
	Data RolePermissionData `json:"data"`
}

type StatusReq struct {
	Id     string `json:"id,optional"`
	Status int64  `json:"status,options=1|2"`
}

type UpdateRoleReq struct {
	Id          int64   `json:"id,optional"`
	Name        *string `json:"name"`
	Code        *string `json:"code"`
	Description *string `json:"description"`
	Status      *int64  `json:"status,options=1|2"`
}

type UserListData struct {
	List  []UserListRsp `json:"list"`
	Total int64         `json:"total"`
}

type UserListReq struct {
	Username string `json:"username,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Nickname string `json:"nickname,optional"`
	Status   int64  `json:"status,optional"`
	PageNo   int64  `json:"pageNo,optional"`
	PageSize int64  `json:"pageSize,optional"`
}

type UserListResponse struct {
	Base
	Data UserListData `json:"data"`
}

type UserListRsp struct {
	Username string  `json:"username"`
	Email    *string `json:"email"`
	Phone    *string `json:"phone"`
	Nickname *string `json:"nickname"`
	Status   *int64  `json:"status"`
	Avatar   *string `json:"avatar"`
}
