// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysPermissionFieldNames          = builder.RawFieldNames(&SysPermission{}, true)
	sysPermissionRows                = strings.Join(sysPermissionFieldNames, ",")
	sysPermissionRowsExpectAutoSet   = strings.Join(stringx.Remove(sysPermissionFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	sysPermissionRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysPermissionFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	sysPermissionModel interface {
		Insert(ctx context.Context, data *SysPermission) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysPermission, error)
		FindOneByCode(ctx context.Context, code string) (*SysPermission, error)
		Update(ctx context.Context, data *SysPermission) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysPermissionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysPermission struct {
		Id        int64          `db:"id"`
		ParentId  int64          `db:"parent_id"`
		Name      string         `db:"name"`
		Code      string         `db:"code"`
		Path      sql.NullString `db:"path"`
		Method    sql.NullString `db:"method"`
		Type      int64          `db:"type"`
		Icon      sql.NullString `db:"icon"`
		Sort      int64          `db:"sort"`
		Status    int64          `db:"status"`
		CreatedAt time.Time      `db:"created_at"`
		UpdatedAt time.Time      `db:"updated_at"`
	}
)

func newSysPermissionModel(conn sqlx.SqlConn) *defaultSysPermissionModel {
	return &defaultSysPermissionModel{
		conn:  conn,
		table: `"public"."sys_permission"`,
	}
}

func (m *defaultSysPermissionModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysPermissionModel) FindOne(ctx context.Context, id int64) (*SysPermission, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysPermissionRows, m.table)
	var resp SysPermission
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysPermissionModel) FindOneByCode(ctx context.Context, code string) (*SysPermission, error) {
	var resp SysPermission
	query := fmt.Sprintf("select %s from %s where code = $1 limit 1", sysPermissionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysPermissionModel) Insert(ctx context.Context, data *SysPermission) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, sysPermissionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ParentId, data.Name, data.Code, data.Path, data.Method, data.Type, data.Icon, data.Sort, data.Status)
	return ret, err
}

func (m *defaultSysPermissionModel) Update(ctx context.Context, newData *SysPermission) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysPermissionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.ParentId, newData.Name, newData.Code, newData.Path, newData.Method, newData.Type, newData.Icon, newData.Sort, newData.Status)
	return err
}

func (m *defaultSysPermissionModel) tableName() string {
	return m.table
}
