// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysRolePermissionFieldNames          = builder.RawFieldNames(&SysRolePermission{}, true)
	sysRolePermissionRows                = strings.Join(sysRolePermissionFieldNames, ",")
	sysRolePermissionRowsExpectAutoSet   = strings.Join(stringx.Remove(sysRolePermissionFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	sysRolePermissionRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysRolePermissionFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	sysRolePermissionModel interface {
		Insert(ctx context.Context, data *SysRolePermission) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysRolePermission, error)
		FindOneByRoleIdPermissionId(ctx context.Context, roleId int64, permissionId int64) (*SysRolePermission, error)
		Update(ctx context.Context, data *SysRolePermission) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysRolePermissionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysRolePermission struct {
		Id           int64 `db:"id"`
		RoleId       int64 `db:"role_id"`
		PermissionId int64 `db:"permission_id"`
	}
)

func newSysRolePermissionModel(conn sqlx.SqlConn) *defaultSysRolePermissionModel {
	return &defaultSysRolePermissionModel{
		conn:  conn,
		table: `"public"."sys_role_permission"`,
	}
}

func (m *defaultSysRolePermissionModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysRolePermissionModel) FindOne(ctx context.Context, id int64) (*SysRolePermission, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysRolePermissionRows, m.table)
	var resp SysRolePermission
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRolePermissionModel) FindOneByRoleIdPermissionId(ctx context.Context, roleId int64, permissionId int64) (*SysRolePermission, error) {
	var resp SysRolePermission
	query := fmt.Sprintf("select %s from %s where role_id = $1 and permission_id = $2 limit 1", sysRolePermissionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, roleId, permissionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRolePermissionModel) Insert(ctx context.Context, data *SysRolePermission) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, sysRolePermissionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.PermissionId)
	return ret, err
}

func (m *defaultSysRolePermissionModel) Update(ctx context.Context, newData *SysRolePermission) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysRolePermissionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.RoleId, newData.PermissionId)
	return err
}

func (m *defaultSysRolePermissionModel) tableName() string {
	return m.table
}
