// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: permission.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionTreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeReq) Reset() {
	*x = PermissionTreeReq{}
	mi := &file_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeReq) ProtoMessage() {}

func (x *PermissionTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeReq.ProtoReflect.Descriptor instead.
func (*PermissionTreeReq) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionTreeReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PermissionTreeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Type          int64                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort          int64                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        int64                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	ParentId      int64                  `protobuf:"varint,10,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Children      []*PermissionTreeItem  `protobuf:"bytes,11,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeItem) Reset() {
	*x = PermissionTreeItem{}
	mi := &file_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeItem) ProtoMessage() {}

func (x *PermissionTreeItem) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeItem.ProtoReflect.Descriptor instead.
func (*PermissionTreeItem) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{1}
}

func (x *PermissionTreeItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionTreeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionTreeItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermissionTreeItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PermissionTreeItem) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PermissionTreeItem) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PermissionTreeItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PermissionTreeItem) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PermissionTreeItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PermissionTreeItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *PermissionTreeItem) GetChildren() []*PermissionTreeItem {
	if x != nil {
		return x.Children
	}
	return nil
}

type PermissionTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PermissionTreeItem  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeResp) Reset() {
	*x = PermissionTreeResp{}
	mi := &file_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeResp) ProtoMessage() {}

func (x *PermissionTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeResp.ProtoReflect.Descriptor instead.
func (*PermissionTreeResp) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{2}
}

func (x *PermissionTreeResp) GetList() []*PermissionTreeItem {
	if x != nil {
		return x.List
	}
	return nil
}

type RoleIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleIdReq) Reset() {
	*x = RoleIdReq{}
	mi := &file_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleIdReq) ProtoMessage() {}

func (x *RoleIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleIdReq.ProtoReflect.Descriptor instead.
func (*RoleIdReq) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{3}
}

func (x *RoleIdReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RolePermissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionIds []int64                `protobuf:"varint,1,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionResp) Reset() {
	*x = RolePermissionResp{}
	mi := &file_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionResp) ProtoMessage() {}

func (x *RolePermissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionResp.ProtoReflect.Descriptor instead.
func (*RolePermissionResp) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{4}
}

func (x *RolePermissionResp) GetPermissionIds() []int64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

var File_permission_proto protoreflect.FileDescriptor

const file_permission_proto_rawDesc = "" +
	"\n" +
	"\x10permission.proto\x12\n" +
	"permission\"'\n" +
	"\x11PermissionTreeReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa5\x02\n" +
	"\x12PermissionTreeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x03R\x04type\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12\x12\n" +
	"\x04sort\x18\b \x01(\x03R\x04sort\x12\x16\n" +
	"\x06status\x18\t \x01(\x03R\x06status\x12\x1b\n" +
	"\tparent_id\x18\n" +
	" \x01(\x03R\bparentId\x12:\n" +
	"\bchildren\x18\v \x03(\v2\x1e.permission.PermissionTreeItemR\bchildren\"H\n" +
	"\x12PermissionTreeResp\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.permission.PermissionTreeItemR\x04list\"$\n" +
	"\tRoleIdReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\";\n" +
	"\x12RolePermissionResp\x12%\n" +
	"\x0epermission_ids\x18\x01 \x03(\x03R\rpermissionIds2\xaa\x01\n" +
	"\n" +
	"Permission\x12O\n" +
	"\x0ePermissionTree\x12\x1d.permission.PermissionTreeReq\x1a\x1e.permission.PermissionTreeResp\x12K\n" +
	"\x12GetRolePermissions\x12\x15.permission.RoleIdReq\x1a\x1e.permission.RolePermissionRespB\x06Z\x04./pbb\x06proto3"

var (
	file_permission_proto_rawDescOnce sync.Once
	file_permission_proto_rawDescData []byte
)

func file_permission_proto_rawDescGZIP() []byte {
	file_permission_proto_rawDescOnce.Do(func() {
		file_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)))
	})
	return file_permission_proto_rawDescData
}

var file_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_permission_proto_goTypes = []any{
	(*PermissionTreeReq)(nil),  // 0: permission.PermissionTreeReq
	(*PermissionTreeItem)(nil), // 1: permission.PermissionTreeItem
	(*PermissionTreeResp)(nil), // 2: permission.PermissionTreeResp
	(*RoleIdReq)(nil),          // 3: permission.RoleIdReq
	(*RolePermissionResp)(nil), // 4: permission.RolePermissionResp
}
var file_permission_proto_depIdxs = []int32{
	1, // 0: permission.PermissionTreeItem.children:type_name -> permission.PermissionTreeItem
	1, // 1: permission.PermissionTreeResp.list:type_name -> permission.PermissionTreeItem
	0, // 2: permission.Permission.PermissionTree:input_type -> permission.PermissionTreeReq
	3, // 3: permission.Permission.GetRolePermissions:input_type -> permission.RoleIdReq
	2, // 4: permission.Permission.PermissionTree:output_type -> permission.PermissionTreeResp
	4, // 5: permission.Permission.GetRolePermissions:output_type -> permission.RolePermissionResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_permission_proto_init() }
func file_permission_proto_init() {
	if File_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_permission_proto_goTypes,
		DependencyIndexes: file_permission_proto_depIdxs,
		MessageInfos:      file_permission_proto_msgTypes,
	}.Build()
	File_permission_proto = out.File
	file_permission_proto_goTypes = nil
	file_permission_proto_depIdxs = nil
}
