// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpc.proto

package server

import (
	"context"

	"speedsterApi/app/role/rpc/internal/logic"
	"speedsterApi/app/role/rpc/internal/svc"
	"speedsterApi/app/role/rpc/pb"
)

type RoleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRoleServer
}

func NewRoleServer(svcCtx *svc.ServiceContext) *RoleServer {
	return &RoleServer{
		svcCtx: svcCtx,
	}
}

func (s *RoleServer) AddUserRole(ctx context.Context, in *pb.UserRole) (*pb.UserRoleResp, error) {
	l := logic.NewAddUserRoleLogic(ctx, s.svcCtx)
	return l.AddUserRole(in)
}

func (s *RoleServer) AssignDefaultRole(ctx context.Context, in *pb.AssignDefaultRoleReq) (*pb.AssignDefaultRoleResp, error) {
	l := logic.NewAssignDefaultRoleLogic(ctx, s.svcCtx)
	return l.AssignDefaultRole(in)
}
