// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type LoginData struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	Time         string `json:"time"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Base
	Data LoginData `json:"data"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken,optional"`
}

type RegisterData struct {
	UserId string `json:"user_id"`
}

type RegisterReq struct {
	Username string  `json:"username"`
	Password string  `json:"password"`
	Email    *string `json:"email,optional"`
	Phone    *string `json:"phone,optional"`
}

type RegisterResp struct {
	Base
	Data RegisterData `json:"data"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type StatusReq struct {
	Id     string `json:"id,optional"`
	Status int64  `json:"status,options=1|2"`
}

type UserListData struct {
	List  []UserListRsp `json:"list"`
	Total int64         `json:"total"`
}

type UserListReq struct {
	Username string `json:"username,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Nickname string `json:"nickname,optional"`
	Status   int64  `json:"status,optional"`
	PageNo   int64  `json:"pageNo,optional"`
	PageSize int64  `json:"pageSize,optional"`
}

type UserListResponse struct {
	Base
	Data UserListData `json:"data"`
}

type UserListRsp struct {
	Username string  `json:"username"`
	Email    *string `json:"email"`
	Phone    *string `json:"phone"`
	Nickname *string `json:"nickname"`
	Status   *int64  `json:"status"`
	Avatar   *string `json:"avatar"`
}
