// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken,optional"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg,omitempty"`
	Data interface{} `json:"data,omitempty"` // .api 中使用 any 对应 Go 的 interface{} 或 泛型 T
}

type StatusReq struct {
	Id     string `json:"id,optional"`
	Status int64  `json:"status,options=1|2"`
}

type UserListReq struct {
	Username string `json:"username,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Nickname string `json:"nickname,optional"`
	Status   int64  `json:"status,optional"`
	PageNo   int    `json:"pageNo,optional"`
	PageSize int    `json:"pageSize,optional"`
}

type UserListRsp struct {
	Username string  `json:"username"`
	Email    *string `json:"email"`
	Phone    *string `json:"phone"`
	Nickname *string `json:"nickname"`
	Status   *int64  `json:"status"`
	Avatar   *string `json:"avatar"`
}
