// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type DelRoleReq struct {
	Id int64 `json:"id,optional"`
}

type NewRoleReq struct {
	Name        string `json:"name,optional"`
	Code        string `json:"code,optional"`
	Description string `json:"description"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type RoleListData struct {
	Name        string
	Code        string
	Desctiption string
	Status      int64
	CreateTime  string
	UpdateTime  string
}

type RoleListReq struct {
	Rolename string `json:"rolename,optional"`
	Code     string `json:"code,optional"`
	Status   int64  `json:"status,optional"`
	PageNo   int    `json:"pageNo,optional"`
	PageSize int    `json:"pageSize,optional"`
}

type RoleListResp struct {
	Base
	Data RoleListData `json:"data"`
}

type UpdateRoleReq struct {
	Id          int64   `json:"id,optional"`
	Name        *string `json:"name"`
	Code        *string `json:"code"`
	Description *string `json:"description"`
	Status      *int64  `json:"status,options=1|2"`
}
