// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"speedsterApi/app/iam/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: AccountLoginHandler(serverCtx),
			},
			{
				// 刷新token
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: RefreshHandler(serverCtx),
			},
			{
				// 注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RedisJwtMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					// 退出登录
					Method:  http.MethodDelete,
					Path:    "/logout",
					Handler: AccountLogoutHandler(serverCtx),
				},
				{
					// 修改用户状态
					Method:  http.MethodPut,
					Path:    "/status",
					Handler: StatusHandler(serverCtx),
				},
				{
					// 用户列表
					Method:  http.MethodPost,
					Path:    "/userlist",
					Handler: UserListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RedisJwtMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					// 新建角色
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: CreateRoleHandler(serverCtx),
				},
				{
					// 删除角色
					Method:  http.MethodDelete,
					Path:    "/delete",
					Handler: DelRoleHandler(serverCtx),
				},
				{
					// 角色列表
					Method:  http.MethodPost,
					Path:    "/rolelist",
					Handler: RoleListHandler(serverCtx),
				},
				{
					// 修改角色
					Method:  http.MethodPut,
					Path:    "/update",
					Handler: UpdateRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/role"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RedisJwtMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					// 角色权限
					Method:  http.MethodPost,
					Path:    "/getRolePermissions",
					Handler: GetRolePermissionsHandler(serverCtx),
				},
				{
					// 权限列表
					Method:  http.MethodPost,
					Path:    "/permissionlist",
					Handler: PermissionListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/permission"),
	)
}
