// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: iam.proto

package server

import (
	"context"

	"speedsterApi/app/iam/rpc/internal/logic"
	"speedsterApi/app/iam/rpc/internal/svc"
	"speedsterApi/app/iam/rpc/pb"
)

type IAMServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIAMServer
}

func NewIAMServer(svcCtx *svc.ServiceContext) *IAMServer {
	return &IAMServer{
		svcCtx: svcCtx,
	}
}

func (s *IAMServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginRsp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *IAMServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterRsp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *IAMServer) UserList(ctx context.Context, in *pb.UserListReq) (*pb.UserListResp, error) {
	l := logic.NewUserListLogic(ctx, s.svcCtx)
	return l.UserList(in)
}

func (s *IAMServer) AddUserRole(ctx context.Context, in *pb.UserRole) (*pb.UserRoleResp, error) {
	l := logic.NewAddUserRoleLogic(ctx, s.svcCtx)
	return l.AddUserRole(in)
}

func (s *IAMServer) AssignDefaultRole(ctx context.Context, in *pb.AssignDefaultRoleReq) (*pb.AssignDefaultRoleResp, error) {
	l := logic.NewAssignDefaultRoleLogic(ctx, s.svcCtx)
	return l.AssignDefaultRole(in)
}

func (s *IAMServer) PermissionTree(ctx context.Context, in *pb.PermissionTreeReq) (*pb.PermissionTreeResp, error) {
	l := logic.NewPermissionTreeLogic(ctx, s.svcCtx)
	return l.PermissionTree(in)
}

func (s *IAMServer) GetRolePermissions(ctx context.Context, in *pb.RoleIdReq) (*pb.RolePermissionResp, error) {
	l := logic.NewGetRolePermissionsLogic(ctx, s.svcCtx)
	return l.GetRolePermissions(in)
}

func (s *IAMServer) UpUserStatus(ctx context.Context, in *pb.UpUserStatusReq) (*pb.UpUserStatusResp, error) {
	l := logic.NewUpUserStatusLogic(ctx, s.svcCtx)
	return l.UpUserStatus(in)
}

func (s *IAMServer) RoleList(ctx context.Context, in *pb.RoleListReq) (*pb.RoleListResp, error) {
	l := logic.NewRoleListLogic(ctx, s.svcCtx)
	return l.RoleList(in)
}

func (s *IAMServer) RoleCreate(ctx context.Context, in *pb.CreateRoleReq) (*pb.CreateRoleResp, error) {
	l := logic.NewRoleCreateLogic(ctx, s.svcCtx)
	return l.RoleCreate(in)
}

func (s *IAMServer) RoleUpdate(ctx context.Context, in *pb.UpdateRoleReq) (*pb.Empty, error) {
	l := logic.NewRoleUpdateLogic(ctx, s.svcCtx)
	return l.RoleUpdate(in)
}

func (s *IAMServer) RoleDelete(ctx context.Context, in *pb.DelRoleReq) (*pb.Empty, error) {
	l := logic.NewRoleDeleteLogic(ctx, s.svcCtx)
	return l.RoleDelete(in)
}
