// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"speedsterApi/app/role/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RedisJwtMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					// 新建角色
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: CreateRoleHandler(serverCtx),
				},
				{
					// 角色列表
					Method:  http.MethodPost,
					Path:    "/rolelist",
					Handler: RoleListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/role"),
	)
}
