// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: iam.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	mi := &file_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRsp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginRsp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginRsp) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *RegisterReq) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

type RegisterRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRsp) Reset() {
	*x = RegisterRsp{}
	mi := &file_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRsp) ProtoMessage() {}

func (x *RegisterRsp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRsp.ProtoReflect.Descriptor instead.
func (*RegisterRsp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	PageNo        int64                  `protobuf:"varint,6,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize      int64                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListReq) Reset() {
	*x = UserListReq{}
	mi := &file_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListReq) ProtoMessage() {}

func (x *UserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListReq.ProtoReflect.Descriptor instead.
func (*UserListReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{4}
}

func (x *UserListReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserListReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserListReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserListReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserListReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *UserListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      *string                `protobuf:"bytes,3,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Phone         *string                `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email         *string                `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Avatar        *string                `protobuf:"bytes,6,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Status        *int64                 `protobuf:"varint,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserItem) Reset() {
	*x = UserItem{}
	mi := &file_iam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserItem) ProtoMessage() {}

func (x *UserItem) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserItem.ProtoReflect.Descriptor instead.
func (*UserItem) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{5}
}

func (x *UserItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserItem) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UserItem) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UserItem) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserItem) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *UserItem) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type UserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*UserItem            `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResp) Reset() {
	*x = UserListResp{}
	mi := &file_iam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResp) ProtoMessage() {}

func (x *UserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResp.ProtoReflect.Descriptor instead.
func (*UserListResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{6}
}

func (x *UserListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserListResp) GetList() []*UserItem {
	if x != nil {
		return x.List
	}
	return nil
}

type UserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	mi := &file_iam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{7}
}

func (x *UserRole) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UserRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleResp) Reset() {
	*x = UserRoleResp{}
	mi := &file_iam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleResp) ProtoMessage() {}

func (x *UserRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleResp.ProtoReflect.Descriptor instead.
func (*UserRoleResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{8}
}

func (x *UserRoleResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type AssignDefaultRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDefaultRoleReq) Reset() {
	*x = AssignDefaultRoleReq{}
	mi := &file_iam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDefaultRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDefaultRoleReq) ProtoMessage() {}

func (x *AssignDefaultRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDefaultRoleReq.ProtoReflect.Descriptor instead.
func (*AssignDefaultRoleReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{9}
}

func (x *AssignDefaultRoleReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AssignDefaultRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDefaultRoleResp) Reset() {
	*x = AssignDefaultRoleResp{}
	mi := &file_iam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDefaultRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDefaultRoleResp) ProtoMessage() {}

func (x *AssignDefaultRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDefaultRoleResp.ProtoReflect.Descriptor instead.
func (*AssignDefaultRoleResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{10}
}

func (x *AssignDefaultRoleResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type PermissionTreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeReq) Reset() {
	*x = PermissionTreeReq{}
	mi := &file_iam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeReq) ProtoMessage() {}

func (x *PermissionTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeReq.ProtoReflect.Descriptor instead.
func (*PermissionTreeReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{11}
}

func (x *PermissionTreeReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PermissionTreeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Type          int64                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort          int64                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        int64                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	ParentId      int64                  `protobuf:"varint,10,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Children      []*PermissionTreeItem  `protobuf:"bytes,11,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeItem) Reset() {
	*x = PermissionTreeItem{}
	mi := &file_iam_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeItem) ProtoMessage() {}

func (x *PermissionTreeItem) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeItem.ProtoReflect.Descriptor instead.
func (*PermissionTreeItem) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{12}
}

func (x *PermissionTreeItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionTreeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionTreeItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermissionTreeItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PermissionTreeItem) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PermissionTreeItem) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PermissionTreeItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PermissionTreeItem) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PermissionTreeItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PermissionTreeItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *PermissionTreeItem) GetChildren() []*PermissionTreeItem {
	if x != nil {
		return x.Children
	}
	return nil
}

type PermissionTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PermissionTreeItem  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeResp) Reset() {
	*x = PermissionTreeResp{}
	mi := &file_iam_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeResp) ProtoMessage() {}

func (x *PermissionTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeResp.ProtoReflect.Descriptor instead.
func (*PermissionTreeResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{13}
}

func (x *PermissionTreeResp) GetList() []*PermissionTreeItem {
	if x != nil {
		return x.List
	}
	return nil
}

type RoleIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleIdReq) Reset() {
	*x = RoleIdReq{}
	mi := &file_iam_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleIdReq) ProtoMessage() {}

func (x *RoleIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleIdReq.ProtoReflect.Descriptor instead.
func (*RoleIdReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{14}
}

func (x *RoleIdReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RolePermissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionIds []int64                `protobuf:"varint,1,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionResp) Reset() {
	*x = RolePermissionResp{}
	mi := &file_iam_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionResp) ProtoMessage() {}

func (x *RolePermissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionResp.ProtoReflect.Descriptor instead.
func (*RolePermissionResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{15}
}

func (x *RolePermissionResp) GetPermissionIds() []int64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

var File_iam_proto protoreflect.FileDescriptor

const file_iam_proto_rawDesc = "" +
	"\n" +
	"\tiam.proto\x12\x03iam\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"f\n" +
	"\bLoginRsp\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\"\x8f\x01\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x01R\x05phone\x88\x01\x01B\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phone\"&\n" +
	"\vRegisterRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xbf\x01\n" +
	"\vUserListReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x17\n" +
	"\apage_no\x18\x06 \x01(\x03R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x03R\bpageSize\"\xfe\x01\n" +
	"\bUserItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\bnickname\x18\x03 \x01(\tH\x00R\bnickname\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x01R\x05phone\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x05 \x01(\tH\x02R\x05email\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x06 \x01(\tH\x03R\x06avatar\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\x03H\x04R\x06status\x88\x01\x01B\v\n" +
	"\t_nicknameB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_emailB\t\n" +
	"\a_avatarB\t\n" +
	"\a_status\"G\n" +
	"\fUserListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12!\n" +
	"\x04list\x18\x02 \x03(\v2\r.iam.UserItemR\x04list\"<\n" +
	"\bUserRole\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\"\"\n" +
	"\fUserRoleResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\"/\n" +
	"\x14AssignDefaultRoleReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"+\n" +
	"\x15AssignDefaultRoleResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\"'\n" +
	"\x11PermissionTreeReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x9e\x02\n" +
	"\x12PermissionTreeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x03R\x04type\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12\x12\n" +
	"\x04sort\x18\b \x01(\x03R\x04sort\x12\x16\n" +
	"\x06status\x18\t \x01(\x03R\x06status\x12\x1b\n" +
	"\tparent_id\x18\n" +
	" \x01(\x03R\bparentId\x123\n" +
	"\bchildren\x18\v \x03(\v2\x17.iam.PermissionTreeItemR\bchildren\"A\n" +
	"\x12PermissionTreeResp\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.iam.PermissionTreeItemR\x04list\"$\n" +
	"\tRoleIdReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\";\n" +
	"\x12RolePermissionResp\x12%\n" +
	"\x0epermission_ids\x18\x01 \x03(\x03R\rpermissionIds2\x8c\x03\n" +
	"\x03IAM\x12%\n" +
	"\x05Login\x12\r.iam.LoginReq\x1a\r.iam.LoginRsp\x12.\n" +
	"\bRegister\x12\x10.iam.RegisterReq\x1a\x10.iam.RegisterRsp\x12/\n" +
	"\bUserList\x12\x10.iam.UserListReq\x1a\x11.iam.UserListResp\x12/\n" +
	"\vAddUserRole\x12\r.iam.UserRole\x1a\x11.iam.UserRoleResp\x12J\n" +
	"\x11AssignDefaultRole\x12\x19.iam.AssignDefaultRoleReq\x1a\x1a.iam.AssignDefaultRoleResp\x12A\n" +
	"\x0ePermissionTree\x12\x16.iam.PermissionTreeReq\x1a\x17.iam.PermissionTreeResp\x12=\n" +
	"\x12GetRolePermissions\x12\x0e.iam.RoleIdReq\x1a\x17.iam.RolePermissionRespB\x06Z\x04./pbb\x06proto3"

var (
	file_iam_proto_rawDescOnce sync.Once
	file_iam_proto_rawDescData []byte
)

func file_iam_proto_rawDescGZIP() []byte {
	file_iam_proto_rawDescOnce.Do(func() {
		file_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_proto_rawDesc), len(file_iam_proto_rawDesc)))
	})
	return file_iam_proto_rawDescData
}

var file_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_iam_proto_goTypes = []any{
	(*LoginReq)(nil),              // 0: iam.LoginReq
	(*LoginRsp)(nil),              // 1: iam.LoginRsp
	(*RegisterReq)(nil),           // 2: iam.RegisterReq
	(*RegisterRsp)(nil),           // 3: iam.RegisterRsp
	(*UserListReq)(nil),           // 4: iam.UserListReq
	(*UserItem)(nil),              // 5: iam.UserItem
	(*UserListResp)(nil),          // 6: iam.UserListResp
	(*UserRole)(nil),              // 7: iam.UserRole
	(*UserRoleResp)(nil),          // 8: iam.UserRoleResp
	(*AssignDefaultRoleReq)(nil),  // 9: iam.AssignDefaultRoleReq
	(*AssignDefaultRoleResp)(nil), // 10: iam.AssignDefaultRoleResp
	(*PermissionTreeReq)(nil),     // 11: iam.PermissionTreeReq
	(*PermissionTreeItem)(nil),    // 12: iam.PermissionTreeItem
	(*PermissionTreeResp)(nil),    // 13: iam.PermissionTreeResp
	(*RoleIdReq)(nil),             // 14: iam.RoleIdReq
	(*RolePermissionResp)(nil),    // 15: iam.RolePermissionResp
}
var file_iam_proto_depIdxs = []int32{
	5,  // 0: iam.UserListResp.list:type_name -> iam.UserItem
	12, // 1: iam.PermissionTreeItem.children:type_name -> iam.PermissionTreeItem
	12, // 2: iam.PermissionTreeResp.list:type_name -> iam.PermissionTreeItem
	0,  // 3: iam.IAM.Login:input_type -> iam.LoginReq
	2,  // 4: iam.IAM.Register:input_type -> iam.RegisterReq
	4,  // 5: iam.IAM.UserList:input_type -> iam.UserListReq
	7,  // 6: iam.IAM.AddUserRole:input_type -> iam.UserRole
	9,  // 7: iam.IAM.AssignDefaultRole:input_type -> iam.AssignDefaultRoleReq
	11, // 8: iam.IAM.PermissionTree:input_type -> iam.PermissionTreeReq
	14, // 9: iam.IAM.GetRolePermissions:input_type -> iam.RoleIdReq
	1,  // 10: iam.IAM.Login:output_type -> iam.LoginRsp
	3,  // 11: iam.IAM.Register:output_type -> iam.RegisterRsp
	6,  // 12: iam.IAM.UserList:output_type -> iam.UserListResp
	8,  // 13: iam.IAM.AddUserRole:output_type -> iam.UserRoleResp
	10, // 14: iam.IAM.AssignDefaultRole:output_type -> iam.AssignDefaultRoleResp
	13, // 15: iam.IAM.PermissionTree:output_type -> iam.PermissionTreeResp
	15, // 16: iam.IAM.GetRolePermissions:output_type -> iam.RolePermissionResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_iam_proto_init() }
func file_iam_proto_init() {
	if File_iam_proto != nil {
		return
	}
	file_iam_proto_msgTypes[2].OneofWrappers = []any{}
	file_iam_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_proto_rawDesc), len(file_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_proto_goTypes,
		DependencyIndexes: file_iam_proto_depIdxs,
		MessageInfos:      file_iam_proto_msgTypes,
	}.Build()
	File_iam_proto = out.File
	file_iam_proto_goTypes = nil
	file_iam_proto_depIdxs = nil
}
