// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: iam.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{0}
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	mi := &file_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRsp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginRsp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginRsp) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *RegisterReq) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

type RegisterRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRsp) Reset() {
	*x = RegisterRsp{}
	mi := &file_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRsp) ProtoMessage() {}

func (x *RegisterRsp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRsp.ProtoReflect.Descriptor instead.
func (*RegisterRsp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	PageNo        int64                  `protobuf:"varint,6,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize      int64                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListReq) Reset() {
	*x = UserListReq{}
	mi := &file_iam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListReq) ProtoMessage() {}

func (x *UserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListReq.ProtoReflect.Descriptor instead.
func (*UserListReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{5}
}

func (x *UserListReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserListReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserListReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserListReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserListReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *UserListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      *string                `protobuf:"bytes,3,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Phone         *string                `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email         *string                `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Avatar        *string                `protobuf:"bytes,6,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Status        *int64                 `protobuf:"varint,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserItem) Reset() {
	*x = UserItem{}
	mi := &file_iam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserItem) ProtoMessage() {}

func (x *UserItem) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserItem.ProtoReflect.Descriptor instead.
func (*UserItem) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{6}
}

func (x *UserItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserItem) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UserItem) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UserItem) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserItem) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *UserItem) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type UserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*UserItem            `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResp) Reset() {
	*x = UserListResp{}
	mi := &file_iam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResp) ProtoMessage() {}

func (x *UserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResp.ProtoReflect.Descriptor instead.
func (*UserListResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{7}
}

func (x *UserListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserListResp) GetList() []*UserItem {
	if x != nil {
		return x.List
	}
	return nil
}

type UserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	mi := &file_iam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{8}
}

func (x *UserRole) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UserRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleResp) Reset() {
	*x = UserRoleResp{}
	mi := &file_iam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleResp) ProtoMessage() {}

func (x *UserRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleResp.ProtoReflect.Descriptor instead.
func (*UserRoleResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{9}
}

func (x *UserRoleResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type AssignDefaultRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDefaultRoleReq) Reset() {
	*x = AssignDefaultRoleReq{}
	mi := &file_iam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDefaultRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDefaultRoleReq) ProtoMessage() {}

func (x *AssignDefaultRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDefaultRoleReq.ProtoReflect.Descriptor instead.
func (*AssignDefaultRoleReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{10}
}

func (x *AssignDefaultRoleReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AssignDefaultRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDefaultRoleResp) Reset() {
	*x = AssignDefaultRoleResp{}
	mi := &file_iam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDefaultRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDefaultRoleResp) ProtoMessage() {}

func (x *AssignDefaultRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDefaultRoleResp.ProtoReflect.Descriptor instead.
func (*AssignDefaultRoleResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{11}
}

func (x *AssignDefaultRoleResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type PermissionTreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeReq) Reset() {
	*x = PermissionTreeReq{}
	mi := &file_iam_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeReq) ProtoMessage() {}

func (x *PermissionTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeReq.ProtoReflect.Descriptor instead.
func (*PermissionTreeReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{12}
}

func (x *PermissionTreeReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PermissionTreeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Type          int64                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort          int64                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        int64                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	ParentId      int64                  `protobuf:"varint,10,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Children      []*PermissionTreeItem  `protobuf:"bytes,11,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeItem) Reset() {
	*x = PermissionTreeItem{}
	mi := &file_iam_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeItem) ProtoMessage() {}

func (x *PermissionTreeItem) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeItem.ProtoReflect.Descriptor instead.
func (*PermissionTreeItem) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{13}
}

func (x *PermissionTreeItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionTreeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionTreeItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermissionTreeItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PermissionTreeItem) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PermissionTreeItem) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PermissionTreeItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PermissionTreeItem) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PermissionTreeItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PermissionTreeItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *PermissionTreeItem) GetChildren() []*PermissionTreeItem {
	if x != nil {
		return x.Children
	}
	return nil
}

type PermissionTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PermissionTreeItem  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeResp) Reset() {
	*x = PermissionTreeResp{}
	mi := &file_iam_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeResp) ProtoMessage() {}

func (x *PermissionTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeResp.ProtoReflect.Descriptor instead.
func (*PermissionTreeResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{14}
}

func (x *PermissionTreeResp) GetList() []*PermissionTreeItem {
	if x != nil {
		return x.List
	}
	return nil
}

type RoleIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleIdReq) Reset() {
	*x = RoleIdReq{}
	mi := &file_iam_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleIdReq) ProtoMessage() {}

func (x *RoleIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleIdReq.ProtoReflect.Descriptor instead.
func (*RoleIdReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{15}
}

func (x *RoleIdReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RolePermissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionIds []int64                `protobuf:"varint,1,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionResp) Reset() {
	*x = RolePermissionResp{}
	mi := &file_iam_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionResp) ProtoMessage() {}

func (x *RolePermissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionResp.ProtoReflect.Descriptor instead.
func (*RolePermissionResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{16}
}

func (x *RolePermissionResp) GetPermissionIds() []int64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

type UpUserStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpUserStatusReq) Reset() {
	*x = UpUserStatusReq{}
	mi := &file_iam_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpUserStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpUserStatusReq) ProtoMessage() {}

func (x *UpUserStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpUserStatusReq.ProtoReflect.Descriptor instead.
func (*UpUserStatusReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{17}
}

func (x *UpUserStatusReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpUserStatusReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpUserStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpUserStatusResp) Reset() {
	*x = UpUserStatusResp{}
	mi := &file_iam_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpUserStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpUserStatusResp) ProtoMessage() {}

func (x *UpUserStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpUserStatusResp.ProtoReflect.Descriptor instead.
func (*UpUserStatusResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{18}
}

func (x *UpUserStatusResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type RoleListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Status        int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	PageNo        int64                  `protobuf:"varint,4,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int64                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListReq) Reset() {
	*x = RoleListReq{}
	mi := &file_iam_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListReq) ProtoMessage() {}

func (x *RoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListReq.ProtoReflect.Descriptor instead.
func (*RoleListReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{19}
}

func (x *RoleListReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleListReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoleListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleListReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *RoleListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RoleListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    string                 `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListItem) Reset() {
	*x = RoleListItem{}
	mi := &file_iam_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListItem) ProtoMessage() {}

func (x *RoleListItem) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListItem.ProtoReflect.Descriptor instead.
func (*RoleListItem) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{20}
}

func (x *RoleListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleListItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoleListItem) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RoleListItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleListItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *RoleListItem) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type RoleListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*RoleListItem        `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListResp) Reset() {
	*x = RoleListResp{}
	mi := &file_iam_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListResp) ProtoMessage() {}

func (x *RoleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListResp.ProtoReflect.Descriptor instead.
func (*RoleListResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{21}
}

func (x *RoleListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RoleListResp) GetList() []*RoleListItem {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReq) Reset() {
	*x = CreateRoleReq{}
	mi := &file_iam_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReq) ProtoMessage() {}

func (x *CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReq.ProtoReflect.Descriptor instead.
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{22}
}

func (x *CreateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRoleReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResp) Reset() {
	*x = CreateRoleResp{}
	mi := &file_iam_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResp) ProtoMessage() {}

func (x *CreateRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResp.ProtoReflect.Descriptor instead.
func (*CreateRoleResp) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{23}
}

func (x *CreateRoleResp) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UpdateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	mi := &file_iam_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateRoleReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoleReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DelRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRoleReq) Reset() {
	*x = DelRoleReq{}
	mi := &file_iam_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRoleReq) ProtoMessage() {}

func (x *DelRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRoleReq.ProtoReflect.Descriptor instead.
func (*DelRoleReq) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{25}
}

func (x *DelRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_iam_proto protoreflect.FileDescriptor

const file_iam_proto_rawDesc = "" +
	"\n" +
	"\tiam.proto\x12\x03iam\"\a\n" +
	"\x05Empty\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"f\n" +
	"\bLoginRsp\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\"\x8f\x01\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x01R\x05phone\x88\x01\x01B\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phone\"&\n" +
	"\vRegisterRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xbf\x01\n" +
	"\vUserListReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x17\n" +
	"\apage_no\x18\x06 \x01(\x03R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x03R\bpageSize\"\xfe\x01\n" +
	"\bUserItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\bnickname\x18\x03 \x01(\tH\x00R\bnickname\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x01R\x05phone\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x05 \x01(\tH\x02R\x05email\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x06 \x01(\tH\x03R\x06avatar\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\x03H\x04R\x06status\x88\x01\x01B\v\n" +
	"\t_nicknameB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_emailB\t\n" +
	"\a_avatarB\t\n" +
	"\a_status\"G\n" +
	"\fUserListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12!\n" +
	"\x04list\x18\x02 \x03(\v2\r.iam.UserItemR\x04list\"<\n" +
	"\bUserRole\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\"\"\n" +
	"\fUserRoleResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\"/\n" +
	"\x14AssignDefaultRoleReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"+\n" +
	"\x15AssignDefaultRoleResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\"'\n" +
	"\x11PermissionTreeReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x9e\x02\n" +
	"\x12PermissionTreeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x03R\x04type\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12\x12\n" +
	"\x04sort\x18\b \x01(\x03R\x04sort\x12\x16\n" +
	"\x06status\x18\t \x01(\x03R\x06status\x12\x1b\n" +
	"\tparent_id\x18\n" +
	" \x01(\x03R\bparentId\x123\n" +
	"\bchildren\x18\v \x03(\v2\x17.iam.PermissionTreeItemR\bchildren\"A\n" +
	"\x12PermissionTreeResp\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.iam.PermissionTreeItemR\x04list\"$\n" +
	"\tRoleIdReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\";\n" +
	"\x12RolePermissionResp\x12%\n" +
	"\x0epermission_ids\x18\x01 \x03(\x03R\rpermissionIds\"9\n" +
	"\x0fUpUserStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\"&\n" +
	"\x10UpUserStatusResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\"\x8b\x01\n" +
	"\vRoleListReq\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\x12\x16\n" +
	"\x06pageNo\x18\x04 \x01(\x03R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x03R\bpageSize\"\xc7\x01\n" +
	"\fRoleListItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x06 \x01(\tR\n" +
	"updateTimeB\x0e\n" +
	"\f_description\"K\n" +
	"\fRoleListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12%\n" +
	"\x04list\x18\x02 \x03(\v2\x11.iam.RoleListItemR\x04list\"Y\n" +
	"\rCreateRoleReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\")\n" +
	"\x0eCreateRoleResp\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\"\x81\x01\n" +
	"\rUpdateRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\"\x1c\n" +
	"\n" +
	"DelRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\x8a\x05\n" +
	"\x03IAM\x12%\n" +
	"\x05Login\x12\r.iam.LoginReq\x1a\r.iam.LoginRsp\x12.\n" +
	"\bRegister\x12\x10.iam.RegisterReq\x1a\x10.iam.RegisterRsp\x12/\n" +
	"\bUserList\x12\x10.iam.UserListReq\x1a\x11.iam.UserListResp\x12/\n" +
	"\vAddUserRole\x12\r.iam.UserRole\x1a\x11.iam.UserRoleResp\x12J\n" +
	"\x11AssignDefaultRole\x12\x19.iam.AssignDefaultRoleReq\x1a\x1a.iam.AssignDefaultRoleResp\x12A\n" +
	"\x0ePermissionTree\x12\x16.iam.PermissionTreeReq\x1a\x17.iam.PermissionTreeResp\x12=\n" +
	"\x12GetRolePermissions\x12\x0e.iam.RoleIdReq\x1a\x17.iam.RolePermissionResp\x12;\n" +
	"\fUpUserStatus\x12\x14.iam.UpUserStatusReq\x1a\x15.iam.UpUserStatusResp\x12/\n" +
	"\bRoleList\x12\x10.iam.RoleListReq\x1a\x11.iam.RoleListResp\x125\n" +
	"\n" +
	"RoleCreate\x12\x12.iam.CreateRoleReq\x1a\x13.iam.CreateRoleResp\x12,\n" +
	"\n" +
	"RoleUpdate\x12\x12.iam.UpdateRoleReq\x1a\n" +
	".iam.Empty\x12)\n" +
	"\n" +
	"RoleDelete\x12\x0f.iam.DelRoleReq\x1a\n" +
	".iam.EmptyB\x06Z\x04./pbb\x06proto3"

var (
	file_iam_proto_rawDescOnce sync.Once
	file_iam_proto_rawDescData []byte
)

func file_iam_proto_rawDescGZIP() []byte {
	file_iam_proto_rawDescOnce.Do(func() {
		file_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_proto_rawDesc), len(file_iam_proto_rawDesc)))
	})
	return file_iam_proto_rawDescData
}

var file_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_iam_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: iam.Empty
	(*LoginReq)(nil),              // 1: iam.LoginReq
	(*LoginRsp)(nil),              // 2: iam.LoginRsp
	(*RegisterReq)(nil),           // 3: iam.RegisterReq
	(*RegisterRsp)(nil),           // 4: iam.RegisterRsp
	(*UserListReq)(nil),           // 5: iam.UserListReq
	(*UserItem)(nil),              // 6: iam.UserItem
	(*UserListResp)(nil),          // 7: iam.UserListResp
	(*UserRole)(nil),              // 8: iam.UserRole
	(*UserRoleResp)(nil),          // 9: iam.UserRoleResp
	(*AssignDefaultRoleReq)(nil),  // 10: iam.AssignDefaultRoleReq
	(*AssignDefaultRoleResp)(nil), // 11: iam.AssignDefaultRoleResp
	(*PermissionTreeReq)(nil),     // 12: iam.PermissionTreeReq
	(*PermissionTreeItem)(nil),    // 13: iam.PermissionTreeItem
	(*PermissionTreeResp)(nil),    // 14: iam.PermissionTreeResp
	(*RoleIdReq)(nil),             // 15: iam.RoleIdReq
	(*RolePermissionResp)(nil),    // 16: iam.RolePermissionResp
	(*UpUserStatusReq)(nil),       // 17: iam.UpUserStatusReq
	(*UpUserStatusResp)(nil),      // 18: iam.UpUserStatusResp
	(*RoleListReq)(nil),           // 19: iam.RoleListReq
	(*RoleListItem)(nil),          // 20: iam.RoleListItem
	(*RoleListResp)(nil),          // 21: iam.RoleListResp
	(*CreateRoleReq)(nil),         // 22: iam.CreateRoleReq
	(*CreateRoleResp)(nil),        // 23: iam.CreateRoleResp
	(*UpdateRoleReq)(nil),         // 24: iam.UpdateRoleReq
	(*DelRoleReq)(nil),            // 25: iam.DelRoleReq
}
var file_iam_proto_depIdxs = []int32{
	6,  // 0: iam.UserListResp.list:type_name -> iam.UserItem
	13, // 1: iam.PermissionTreeItem.children:type_name -> iam.PermissionTreeItem
	13, // 2: iam.PermissionTreeResp.list:type_name -> iam.PermissionTreeItem
	20, // 3: iam.RoleListResp.list:type_name -> iam.RoleListItem
	1,  // 4: iam.IAM.Login:input_type -> iam.LoginReq
	3,  // 5: iam.IAM.Register:input_type -> iam.RegisterReq
	5,  // 6: iam.IAM.UserList:input_type -> iam.UserListReq
	8,  // 7: iam.IAM.AddUserRole:input_type -> iam.UserRole
	10, // 8: iam.IAM.AssignDefaultRole:input_type -> iam.AssignDefaultRoleReq
	12, // 9: iam.IAM.PermissionTree:input_type -> iam.PermissionTreeReq
	15, // 10: iam.IAM.GetRolePermissions:input_type -> iam.RoleIdReq
	17, // 11: iam.IAM.UpUserStatus:input_type -> iam.UpUserStatusReq
	19, // 12: iam.IAM.RoleList:input_type -> iam.RoleListReq
	22, // 13: iam.IAM.RoleCreate:input_type -> iam.CreateRoleReq
	24, // 14: iam.IAM.RoleUpdate:input_type -> iam.UpdateRoleReq
	25, // 15: iam.IAM.RoleDelete:input_type -> iam.DelRoleReq
	2,  // 16: iam.IAM.Login:output_type -> iam.LoginRsp
	4,  // 17: iam.IAM.Register:output_type -> iam.RegisterRsp
	7,  // 18: iam.IAM.UserList:output_type -> iam.UserListResp
	9,  // 19: iam.IAM.AddUserRole:output_type -> iam.UserRoleResp
	11, // 20: iam.IAM.AssignDefaultRole:output_type -> iam.AssignDefaultRoleResp
	14, // 21: iam.IAM.PermissionTree:output_type -> iam.PermissionTreeResp
	16, // 22: iam.IAM.GetRolePermissions:output_type -> iam.RolePermissionResp
	18, // 23: iam.IAM.UpUserStatus:output_type -> iam.UpUserStatusResp
	21, // 24: iam.IAM.RoleList:output_type -> iam.RoleListResp
	23, // 25: iam.IAM.RoleCreate:output_type -> iam.CreateRoleResp
	0,  // 26: iam.IAM.RoleUpdate:output_type -> iam.Empty
	0,  // 27: iam.IAM.RoleDelete:output_type -> iam.Empty
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_iam_proto_init() }
func file_iam_proto_init() {
	if File_iam_proto != nil {
		return
	}
	file_iam_proto_msgTypes[3].OneofWrappers = []any{}
	file_iam_proto_msgTypes[6].OneofWrappers = []any{}
	file_iam_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_proto_rawDesc), len(file_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_proto_goTypes,
		DependencyIndexes: file_iam_proto_depIdxs,
		MessageInfos:      file_iam_proto_msgTypes,
	}.Build()
	File_iam_proto = out.File
	file_iam_proto_goTypes = nil
	file_iam_proto_depIdxs = nil
}
