name: Deploy Speedster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Install goctl
        run: |
          go install github.com/zeromicro/go-zero/tools/goctl@latest

      - name: Install goctl-swagger
        run: |
          go install github.com/zeromicro/goctl-swagger@latest

      - name: Generate Iam Swagger
        run: |
          mkdir -p app/iam/api/docs
          goctl api plugin \
            -plugin goctl-swagger="swagger -filename iam.json" \
            -api app/iam/api/iam.api \
            -dir app/iam/api/docs

    

      ################################
      # 编译
      ################################

      - name: Build Gateway
        working-directory: app/gateway
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -ldflags="-s -w" \
          -tags no_k8s \
          -o gateway .

      - name: Build IamApi
        working-directory: app/iam/api
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -ldflags="-s -w" \
          -tags no_k8s \
          -o iam-api .

      - name: Build IamRpc
        working-directory: app/iam/rpc
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -ldflags="-s -w" \
          -tags no_k8s \
          -o iam-rpc .

      - name: Build Gateway
        working-directory: app/gateway
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -ldflags="-s -w" \
          -tags no_k8s \
          -o gateway .

      
          

      ################################
      # 上传文件
      ################################
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Create target dir
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -p ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "mkdir -p \
            /data/github/pgsql \
            /data/github/common/casbin \
            /data/github/app/gateway \
            /data/github/app/iam/api \
            /data/github/app/iam/rpc \ "

      - name: Upload deployFiles
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            deploy/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/

      - name: Upload initSql
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            common/init/init.sql \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/pgsql/gavin.sql

      - name: Upload casBin
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            common/casbin/model.conf \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/common/casbin/
          

      - name: Upload gateway
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            app/gateway/gateway \
            app/gateway/etc \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/app/gateway/

      - name: Upload iamApi
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            app/iam/api/iam-api \
            app/iam/api/etc \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/app/iam/api/

      - name: Upload iamRpc
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            app/iam/rpc/iam-rpc \
            app/iam/rpc/etc \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/app/iam/rpc/

      




      ################################
      # docker compose
      ################################
      - name: Restart services
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /data/github
            docker compose down
            docker compose up -d --build