name: Deploy Speedster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Install goctl
        run: |
          go install github.com/zeromicro/go-zero/tools/goctl@latest

      - name: Install goctl-swagger
        run: |
          go install github.com/zeromicro/goctl-swagger@latest

      - name: Generate User Swagger
        run: |
          mkdir -p app/user/api/docs
          goctl api plugin \
            -plugin goctl-swagger="swagger -filename user.json" \
            -api app/user/api/user.api \
            -dir app/user/api/docs

      - name: Generate Role Swagger
        run: |
          mkdir -p app/role/api/docs
          goctl api plugin \
            -plugin goctl-swagger="swagger -filename role.json" \
            -api app/role/api/role.api \
            -dir app/role/api/docs
          

      ################################
      # 编译
      ################################
      - name: Build UserApi
        working-directory: app/user/api
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -ldflags="-s -w" \
          -tags no_k8s \
          -o user-api .

      - name: Build UserRpc
        working-directory: app/user/user
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -ldflags="-s -w" \
          -tags no_k8s \
          -o user-rpc .

      - name: Build Gateway
        working-directory: app/gateway
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -ldflags="-s -w" \
          -tags no_k8s \
          -o gateway .

      - name: Build RoleApi
        working-directory: app/role/api
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -ldflags="-s -w" \
          -tags no_k8s \
          -o role-api .

      ################################
      # 上传文件
      ################################
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Create target dir
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -p ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "mkdir -p \
            /data/github/pgsql \
            /data/github/common/casbin \
            /data/github/app/gateway \
            /data/github/app/user/api \
            /data/github/app/user/rpc \
            /data/github/app/role/api \
            /data/github/app/role/rpc"

      - name: Upload deployFiles
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            deploy \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/

      - name: Upload initSql
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            common/init/init.sql \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/pgsql/gavin.sql

      - name: Upload casbin
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            common/casbin/model.conf \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/common/casbin/

      - name: Upload userApi
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            app/user/api/user-api \
            app/user/api/etc \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/app/user/api/

      - name: Upload userRpc
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            app/user/user/user-rpc \
            app/user/user/etc \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/app/user/rpc/

      - name: Upload roleApi
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            app/role/api/role-api \
            app/role/api/etc \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/app/role/api/

      - name: Upload gateway
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_PORT }}" \
            app/gateway/gateway \
            app/gateway/etc \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/data/github/app/gateway/


      ################################
      # docker compose
      ################################
      - name: Restart services
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /data/github
            docker compose down
            docker compose up -d --build