// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: iam.proto

package iam

import (
	"context"

	"speedsterApi/app/iam/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssignDefaultRoleReq  = pb.AssignDefaultRoleReq
	AssignDefaultRoleResp = pb.AssignDefaultRoleResp
	LoginReq              = pb.LoginReq
	LoginRsp              = pb.LoginRsp
	PermissionTreeItem    = pb.PermissionTreeItem
	PermissionTreeReq     = pb.PermissionTreeReq
	PermissionTreeResp    = pb.PermissionTreeResp
	RegisterReq           = pb.RegisterReq
	RegisterRsp           = pb.RegisterRsp
	RoleIdReq             = pb.RoleIdReq
	RolePermissionResp    = pb.RolePermissionResp
	UserItem              = pb.UserItem
	UserListReq           = pb.UserListReq
	UserListResp          = pb.UserListResp
	UserRole              = pb.UserRole
	UserRoleResp          = pb.UserRoleResp

	IAM interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRsp, error)
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRsp, error)
		UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
		AddUserRole(ctx context.Context, in *UserRole, opts ...grpc.CallOption) (*UserRoleResp, error)
		AssignDefaultRole(ctx context.Context, in *AssignDefaultRoleReq, opts ...grpc.CallOption) (*AssignDefaultRoleResp, error)
		PermissionTree(ctx context.Context, in *PermissionTreeReq, opts ...grpc.CallOption) (*PermissionTreeResp, error)
		GetRolePermissions(ctx context.Context, in *RoleIdReq, opts ...grpc.CallOption) (*RolePermissionResp, error)
	}

	defaultIAM struct {
		cli zrpc.Client
	}
)

func NewIAM(cli zrpc.Client) IAM {
	return &defaultIAM{
		cli: cli,
	}
}

func (m *defaultIAM) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRsp, error) {
	client := pb.NewIAMClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultIAM) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRsp, error) {
	client := pb.NewIAMClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultIAM) UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := pb.NewIAMClient(m.cli.Conn())
	return client.UserList(ctx, in, opts...)
}

func (m *defaultIAM) AddUserRole(ctx context.Context, in *UserRole, opts ...grpc.CallOption) (*UserRoleResp, error) {
	client := pb.NewIAMClient(m.cli.Conn())
	return client.AddUserRole(ctx, in, opts...)
}

func (m *defaultIAM) AssignDefaultRole(ctx context.Context, in *AssignDefaultRoleReq, opts ...grpc.CallOption) (*AssignDefaultRoleResp, error) {
	client := pb.NewIAMClient(m.cli.Conn())
	return client.AssignDefaultRole(ctx, in, opts...)
}

func (m *defaultIAM) PermissionTree(ctx context.Context, in *PermissionTreeReq, opts ...grpc.CallOption) (*PermissionTreeResp, error) {
	client := pb.NewIAMClient(m.cli.Conn())
	return client.PermissionTree(ctx, in, opts...)
}

func (m *defaultIAM) GetRolePermissions(ctx context.Context, in *RoleIdReq, opts ...grpc.CallOption) (*RolePermissionResp, error) {
	client := pb.NewIAMClient(m.cli.Conn())
	return client.GetRolePermissions(ctx, in, opts...)
}
