// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}
